use "${OUT}/append all_fin.dta",clear
label variable bathing "functioning of bathing "
label variable continence "functioning of continence "
label variable dressing "functioning of dressing "
label variable feeding "functioning of self-feeding "
label variable toileting "functioning of toileting "
label variable transferring "functioning of indoor transferring "
label variable arthritis "suffering from arthritis ?"
label variable bedsore "suffering from bedsore ?"
label variable cancer "suffering from cancer ?"
label variable strokecvd "suffering from stroke or cvd ?"
label variable dementia "suffering from dementia ?"
label variable diabetes "suffering from diabetes ?"
label variable ulcer "suffering from gastric or duodenal ulcer ?"
label variable glaucoma "suffering from glaucoma or cataract ?"
label variable heartdisea "suffering from heart disease "
label variable hypertension "suffering from hypertension ?"
label variable parkinson "suffering from parkinson's disease ?"
label variable copd "suffering from bronchitis, emphysema, pneumonia ?"
label variable prostatetumor "suffering from prostate tumor ?"
label variable psycho "psycho index"
label variable tb "suffering from tuberculosis ?"
label variable Dhhgener "number of generations living in the household when the elderly died"
label variable Dlivarr "primary living arrangement of the deceased elder in the last year of life"
label variable hhsize "number of people who living with the respondent "
label variable Dbedday "days of being bedridden "
label variable Dbedri "bedridden or nor "
label variable marital "marital status of the deceased elder at death"
label variable Dplace "place of death"
label variable dril "drinking behavior"
label variable smkl "smoking behavior"
label variable DOOPhexp "total amount of out-of-pocket"
label variable hexpFampaid "total medical cost (rmb) in the last year of the life by family"
label variable hexpPayer "who mainly paid the medical cost for the deceased elder?"
label variable Dhavedoc "if the deceased elder was from rural, was there a doctor in the village?"
label variable Dhavedoclic "did the village doctor have a license?"
label variable hhIncome "yearly per capita income of the family of the deceased elder"
label variable DcarehexpM "number of days cared for the deceased by primary caregiver in the last month of"
label variable Dcaredayneede "days the deceased perosn needing full care "
label variable DcarehexpM "total direct cost for caregiving in the last month of life"
label variable Dcargiv "first caregiver "
label variable Dpayercare "who mainly paid the care serivces ?"


label variable intdate "interview date"
label variable lostsample "sample that lost to followup"
label variable deathstatus "death status"
label variable deathsample "sample that died during 98-18"
label variable dthdate "death date"
label variable yearin "interview year"
label variable monthin "interview month"
label variable dayin "interview day"
label variable housework "do you do house work at present?"
label variable fieldwork "do you do fieldwork at present?"
label variable gardenwork "do you do gardenwork at present?"
label variable reading "do you do reading work at present?"
label variable pets "do you raise pets at present?"
label variable majong "do you do majong present?"
label variable tv "do you watch tv at present?"
label variable socialactivity "do you do socialactivity at present?"
label variable interview_baseline "interview date at baseline"
label variable dthyear "death year"
label variable dthmonth "death month"
label variable dthday "death day"
label variable agebase "age at baseline "

label variable hhIncomepercap "annual household income per capita"
label variable insurancePubMed "public medical insurance"
label variable insuranceCommMed "commercial medical insurance"
label variable insuranceMed "medical insurance (public and commerical)"
label variable insurancePubRetire "public retirment pension"
label variable insuranceCommRetire "commercial retirment pension"
label variable insuranceRetire "pension (public and commercial)"
label variable hexpFinanceissue ""
label variable hexpFampaidOP "last year outpatient health expenditure family paid"
label variable hexpFampaidIP "last year inpatient health expenditure family paid"
label variable hexpIndpaidOP "last year outpatient health expenditure individual paid"
label variable hexpIndpaidIP "last year inpatient health expenditure individual paid"
label variable hexpIndpaid "last year total health expenditure individual paid"
label variable nursingLiving "living in health institute"
label variable nursingCost "year of being admitted to the institute"
label variable nursingCover "who mainly paid for the cost for institute?"
label variable retiredYear "retired year"
label variable pensionYearly "what is your annual pension from old age insurance at present?"
label variable srhealth  "self reported health"
label variable pa "physical activity"
label variable leisureMiss "missing in leisure"
label variable leisure "leisure index"
label variable adl "ADL"
label variable meat "eating frequency of meat"
label variable fish "eating frequency of fish"
label variable egg "eating frequency of egg"
label variable bean "eating frequency of bean"
label variable veg "eating frequency of vegetables"
label variable fruit "eating frequency of fruit"

 

label variable saltveg "eating frequency of salted vegetables"
label variable sugar "eating frequency of sugar"
label variable tea "eating frequency of tea"
label variable garlic "eating frequency of garlic"
label variable weight "weight"

label variable numchild "number of children"
label variable nurisngYear "year of being admitted to the nursing home"

label variable mmse "MMSE score--congitive failure related"
label variable hunchbacked ""
label variable DcaredayM  "monthly care dates"
label variable DcarehexpM "health expenditure in care in the last month"
label variable DcarehexpD "daily health expenditure in care"
label variable hexpFinanceissue  "get adequate medical service at present"
label variable ablephy "did interviewee able to participate in physical check?"
label variable ablephyreas "the reason of unable to participate physical check"
label variable height ""
label variable adlMiss "missing in ADL index"
label variable adlSum "ADL index"
label variable hearingloss "hearing loss"
label variable armlength ""
label variable gender ""
label variable bmi ""
label variable bmiCat ""
label variable retiredWPension "retired with pension?"
label variable residence ""
label variable bpl "Blood Pressure Level"
label variable cataract "suffer from cataratct"
label variable psyMiss "missing in psy inde"
label variable psy7 "be happy as younger"
label variable psy6 "feel useless with age"
label variable psy5 "make own decision"
label variable psy4 "feel lonely and isolated"
label variable psy3 "feel fearful or anxious"
label variable psy2 "keep my belongings neat and clean"
label variable psy1 "look on the bright side of things"
label variable ci "MMSE score"
label variable ciBi "cognitive failure"
label variable ciCat "cognitive failure"
label variable ciMissing "missing in MMSE"


label variable hr "heart rate"
label variable SBP "systolic blood pressure"
label variable DBP "diastolic blood pressure"


label define coresidence 1 "with household members" 2"alone" 3"In an institution" 
label define gender 1"male" 0"female"
label define residence   1 "urban (city or town)" 2"rural"
label define bmiCat 1"underweight" 2"normal" 3"overweight"
label define yesno 1"yes" 0"no"
label define psy 1"Excellent" 2"good" 3"fair" 4"worse" 5"bad"
label define occu 0"professional and technical personnel" 1"governmental, institutional or manageri" 2"agriculture, forest, animal husbandry" 3"fishery worker" 4"industrial worker" 5"commercial or service worker" 6"military personnel" 7"housework" 8"others"
label define bpl 1 "hypotension" 2 "Normal" 3 "Prehypertension" 4 "Stage I Hypertesnion" 5 "Stage II Hypertension" 
label define hearingloss 0"no" 1"yes,one ears" 2"yes, both ears"
label define Dcargiv 1 "spouse"	2 "children/their spouses"	3 "grandchildren/their spouses"	4 "other family members"	5 "friends"	6 "social service providers"	7 "nurse/maid"	8 "no body"	9 "do not need care"
label define food 1"everday or excepte winter"  2"occasionally"   3"rarely or never"
label define dril  1 "never" 2 "former" 3 "current & light" 4 "current & heavy"
label define Dhavedoclic 1 "licensed with college degree" 2"licensed without college degree"  3"unlicensed"
label define hexpPayer 1"no secure" 2"self/spouse"  3"children/others" 4"insurance/health services"
label define ablephyreas 1 "visually impaired, but can hear"	2 "hearing impaired, but can see"	3 "visually and hearing impaired"	4 "paralyzed"	5 "didn't wish to participate"	6 "could not understand due to cognitive i"	7 "suffering from illness at moment"	8 "others"
label define Dplace 1"home" 2"hospital" 3"institutes" 4"others"
label define srh 1 "Very good" 2 "good" 3 "fair" 4"Bad/Very bad"
label define marital 1 "currently married and living with spouse" 2"separted, divorced or never married" 3"widowed"
label define smkl 1 "never" 2 "former" 3 "light current" 4 "heavy current"
label define pa 1 "current & start < 50" 2 "current & start >=50" 3 "former" 4 "never"
label define hyper 0"no"   1"yes,but no disability" 2"yes, cause more or less disability" 3"yes, cause serious disability"
label define hexpayer 1 "free public medical services" 2 "self" 3 "spouse" 4 "children or grandchilren" 5 "cooperative medical scheme" 6 "state or collectives subsidy" 7 "medical insurance"  8 "no money go to hospital" 9 "others"


foreach k in coresidence	gender	residence	bmiCat	 		occu	bpl	hearingloss	Dcargiv	dril	Dhavedoclic	hexpPayer	ablephyreas	Dplace		marital	smkl	pa {
	label values `k' `k'
}
//hexpayer	
label values  hypertension diabetes heartdisea strokecvd copd tb cataract glaucoma cancer prostatetumor ulcer parkinson bedsore arthritis  dementia   hyper 

label values srhealth srhealthSopuse  srh

label values psy1 psy2 psy3 psy4 psy5 psy6 psy7  psy 
label values veg fruit  food 

recode     hunchbacked  deathstatus insuranceCommRetire  insuranceCommMed  adl hexpFinanceissue  ablephy  Dhavedoc nursingLiving   insuranceMed  lostsample  deathsample retiredWPension insuranceRetire Dbedri (0 2 3= 0) 
label values  Dbedri insuranceRetire  hunchbacked  deathstatus insuranceCommRetire  insuranceCommMed  adl hexpFinanceissue  ablephy  Dhavedoc nursingLiving   insuranceMed  lostsample  deathsample retiredWPension yesno

save,replace
